### ISSUE TITLE
Site-to-site Two-Way Replication

### ISSUE THREAD

**Issue by ICON-GIT** [projectkudu/AzureSiteReplicator#10]
Hi David.
Your extension to replicate one azure web app to another is awesome.
May I ask: Would you think that two web apps, replicating to each other can cause problems?
Regards

**Comment by davidebbo** [comment]
I have never tried this. The risk is that it would get stuck in some kind of loop deploying back and forth. In theory it should be ok because if there is nothing different, it shouldn't deploy anything, stopping the cycle.

**Comment by ehamai** [comment]
I've never tried it either, but I think there's probably a risk of data loss if you have 2 Web Deploy endpoints syncing to each other.  For instance, S1 could send 10% of its files to S2, which triggers a sync from S2 to S1.  At this point S2 only knows about 10% of the total files and then starts deleting the remaining files on S1.  It's hard to say exactly what would happen, but I don't think it's a good idea.

**Comment by ICON-GIT** [comment]
Thank you.
As you said, the extension was not designed to handle this requirement.
