### ISSUE TITLE
Azure web app not visible in new portal

### ISSUE THREAD

**Issue by chilli-andrew** [projectkudu/AzureSiteReplicator#11]
Hi,

Forgive me if I have posted this issue in the incorrect place..  A number of my web apps that appear in the old azure management website are not appearing on in the new portal, the azure app service support website and in cloud explorer in visual studio.  An example of one site experiencing such an issue is adisa.azurewebsites.net.

**Comment by davidebbo** [comment]
Correct place is https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview.

**Comment by davidebbo** [comment]
I did a sync on your subscription which should fix it, so please do check (may take a few minutes). But if it still happens, please start forum thread.

**Comment by chilli-andrew** [comment]
Thanks David,  that seems to have done the trick.  Very much appreciated.
