### ISSUE TITLE
No route registered for '/sitereplicator/'

### ISSUE THREAD

**Issue by esalwin** [projectkudu/AzureSiteReplicator#15]
When we try to run Site Replicator in our production App Service, we get the following error:

No route registered for '/sitereplicator/'

We followed all of the README.md instructions and ensured no "webpages:Enabled" app setting.  We also tried un-installing and re-installing the extension.

That said, Site Replicator works great in our staging App Service.   If relevant, the two major differences between production and staging are:

- Production originally ran on the Premium tier.  But we downgraded to the Standard tier to install Site Replicator.
- Production runs across two instances.

**Comment by davidebbo** [comment]
Have you tried restarting the app?

**Comment by esalwin** [comment]
Yup!  We tried restarting immediately after adding the extension and also after letting the extension "incubate" for a day.

**Comment by davidebbo** [comment]
Check your applicationhost.config per https://github.com/projectkudu/kudu/wiki/Azure-Site-Extensions#finding-your-applicationhostconfig.

Does it have something like this? Try comparing the working with non-working case:

        <application path="/sitereplicator" preloadEnabled="false" applicationPool="~1yoursitename">
          <virtualDirectory path="/" physicalPath="D:\home\SiteExtensions\sitereplicator" />
        </application>

**Comment by esalwin** [comment]
Thanks!  The <virtualDirectory> element (you posted above) was missing from our applicationhost.config due to an unrelated transform error from applicationhost.xdt.

We fixed applicationhost.xdt, restarted the App Service, and successfully added Site Replicator :)

**Comment by davidebbo** [comment]
Awesome!
