### ISSUE TITLE
Sync isn't always running when the extension isn't on the screen

### ISSUE THREAD

**Issue by mrdenny** [projectkudu/AzureSiteReplicator#17]
I just had a situation when the sync hadn't run in a while on one site for a while. As soon as I looked at the properties of the extention it kicked off the sync.

**Comment by davidebbo** [comment]
That's a sign that you don't have Always On enabled. See the Readme for details.

**Comment by mrdenny** [comment]
Yep, that was it. It was enabled for all the other copies, but not the "hub" copy.  Thanks.
