### ISSUE TITLE
Error when clicking "submit" and no PublishSettings file was selected

### ISSUE THREAD

**Issue by miparnisari** [projectkudu/AzureSiteReplicator#4]
![image](https://cloud.githubusercontent.com/assets/5374887/5977556/d53829cc-a877-11e4-9e64-61d61cf0a4d9.png)

![image](https://cloud.githubusercontent.com/assets/5374887/5977558/d9019ff2-a877-11e4-8fec-1287a4237997.png)

**Comment by davidebbo** [comment]
Yes, we should fix this.
