### ISSUE TITLE
How is the replicator activated? How can I trigger a replication?

### ISSUE THREAD

**Issue by miparnisari** [projectkudu/AzureSiteReplicator#5]

**Comment by davidebbo** [comment]
It happens automatically when it detects changes to the wwwroot folder of the source site.

**Comment by miparnisari** [comment]
Including for example the removal of the wwwroot folder itself?

**Comment by davidebbo** [comment]
No, that probably won't work, and is really not a common scenario. The scenario it's designed for is to do normal publishing to master site (WebDeploy, git, FTP), and have the bits propagate to other sites.

**Comment by miparnisari** [comment]
Oh ok, thanks!
